version: '3.8'

services:
  db:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: localhost
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
